"""Add AI provider and encryption fields

Revision ID: b159d763f7fd
Revises: 38335ec7c877
Create Date: 2026-05-02 15:03:36.054659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b159d763f7fd'
down_revision: Union[str, Sequence[str], None] = '38335ec7c877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('ai_provider', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('encrypted_gemini_api_key', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('llm_model_override', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'llm_model_override')
    op.drop_column('businesses', 'encrypted_gemini_api_key')
    op.drop_column('businesses', 'ai_provider')
    # ### end Alembic commands ###
